// <auto-generated />
using System;
using CareerAdvisor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerAdvisor.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CareerAdvisorDbContext))]
    [Migration("20260813014828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CareerAdvisor.Core.Models.CareerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CareerProfiles");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.CareerRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecommendationSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId");

                    b.HasIndex("RecommendationSessionId");

                    b.ToTable("CareerRecommendations");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.LearningRoadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CareerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareerProfileId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("LearningRoadmaps");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.RecommendationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("RecommendationSessions");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.RoadmapStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LearningRoadmapId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningRoadmapId");

                    b.ToTable("RoadmapSteps");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcademicLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Programme")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.StudentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("StudentSkills");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.CareerRecommendation", b =>
                {
                    b.HasOne("CareerAdvisor.Core.Models.CareerProfile", "Career")
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerAdvisor.Core.Models.RecommendationSession", null)
                        .WithMany("Recommendations")
                        .HasForeignKey("RecommendationSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.LearningRoadmap", b =>
                {
                    b.HasOne("CareerAdvisor.Core.Models.CareerProfile", null)
                        .WithMany()
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerAdvisor.Core.Models.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.RecommendationSession", b =>
                {
                    b.HasOne("CareerAdvisor.Core.Models.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.RoadmapStep", b =>
                {
                    b.HasOne("CareerAdvisor.Core.Models.LearningRoadmap", null)
                        .WithMany("Steps")
                        .HasForeignKey("LearningRoadmapId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.StudentSkill", b =>
                {
                    b.HasOne("CareerAdvisor.Core.Models.StudentProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.LearningRoadmap", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.RecommendationSession", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("CareerAdvisor.Core.Models.StudentProfile", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
